### ISSUE TITLE
Crash when using sysroot provided by rustc

### ISSUE THREAD

**Issue by dkm** [rust-lang/rustc_codegen_gcc#47] opened 2021-07-07 18:11 UTC
```
$ RUST_BACKTRACE=1/.../rustc-cg-gcc-master-20210703/bin/rustc -C panic=abort -Z codegen-backend=librustc_codegen_gcc.so -C debuginfo=1 -o /tmp/output.s --crate-type bin --color=always /tmp/ex.rs
warning: unused variable: `i`
 --> /tmp/ex.rs:1:9
  |
1 | fn toto(i: i32) {
  |         ^ help: if this is intentional, prefix it with an underscore: `_i`
  |
  = note: `#[warn(unused_variables)]` on by default

thread 'rustc' panicked at 'not implemented', src/builder.rs:1527:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f586d79d183d144e0cbf519e29247f36670e2076/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/f586d79d183d144e0cbf519e29247f36670e2076/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/f586d79d183d144e0cbf519e29247f36670e2076/library/core/src/panicking.rs:50:5
   3: rustc_codegen_ssa::mir::codegen_mir
   4: rustc_codegen_ssa::base::codegen_instance
   5: <rustc_middle::mir::mono::MonoItem as rustc_codegen_ssa::mono_item::MonoItemExt>::define
   6: rustc_codegen_gcc::base::compile_codegen_unit::module_codegen
   7: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
   8: rustc_codegen_gcc::base::compile_codegen_unit
   9: rustc_codegen_ssa::base::codegen_crate
  10: <rustc_codegen_gcc::GccCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  11: rustc_interface::passes::QueryContext::enter
  12: rustc_interface::queries::Queries::ongoing_codegen
  13: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  14: rustc_span::with_source_map
  15: rustc_interface::interface::create_compiler_and_run
  16: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.55.0-nightly (f586d79d1 2021-06-13) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z codegen-backend=librustc_codegen_gcc.so -C panic=abort -C debuginfo=1 --crate-type bin

query stack during panic:
end of query stack
warning: 1 warning emitted
```
Same command with the `--sysroot` pointing to cg_gcc's sysroot works:
```
$ rustc-cg-gcc-master-20210703/bin/rustc -C panic=abort -Z codegen-backend=librustc_codegen_gcc.so --sysroot /.../rustc-cg-gcc-master-20210703/sysroot -C debuginfo=1 -o /tmp/output.s --crate-type bin --color=always /tmp/ex.rs
```

**Comment by antoyo** [comment] 2021-07-07 18:25
As I mentionned elsewhere, this is caused by unwinding not being implemented.
Are you sure `panic=abort` is specified everywhere?
Perhaps the sysroot provided by rustc is compiled with unwinding support and this enables it in your case, disregarding `-C panic=abort`?

**Comment by dkm** [comment] 2021-07-07 18:44
I'm using only one command, so the `-Cpanic=abort` is "everywhere". But maybe you mean somewhere else ?

**Comment by bjorn3** [comment] 2021-07-07 18:49
cg_gcc is not abi compatible with cg_llvm. At https://github.com/antoyo/rustc_codegen_gcc/blob/8b191d709009bb74e525f1f59c302c5233bdad4c/src/abi.rs#L156 the `on_stack` field is not handled. If it is true, the value needs to be passed at a stack offset determined by the calling convention instead of as a pointer. This is how large C structs are passed.

**Comment by bjorn3** [comment] 2021-07-07 18:54
> I'm using only one command, so the -Cpanic=abort is "everywhere". But maybe you mean somewhere else ?

I think @antoyo means that all dependencies have to be compiled with `-Cpanic=abort` too, including the sysroot. cg_ssa tries to unconditionally set a personality function if any cleanup blocks exist, even if you compile with `-Cpanic=abort`. MIR imported from a crate compiled with `-Cpanic=unwind` will contain cleanup blocks, even if they won't be used during codegen of the current crate.

**Comment by dkm** [comment] 2021-07-07 19:07
Ok, clearer now, thanks!

**Comment by antoyo** [comment] 2021-07-07 19:10
@dkm : So, is there anything else I can do to help the integration in CE? Or will you just go without the binary feature?

**Comment by bjorn3** [comment] 2022-03-30 19:21
I think this would have been fixed by https://github.com/rust-lang/rustc_codegen_gcc/pull/135. Someone will need to check though.

**Comment by antoyo** [comment] 2024-02-08 22:01
Closing since it should be fixed. Feel free to reopen or open another issue if you have any other issues.

**Closed by antoyo** 2024-02-08 22:01 UTC
